image: alpine/latest
packages:
- qemu-aarch64
- qemu-openrc
sources:
- https://git.sr.ht/~mcf/cproc
- https://git.sr.ht/~mcf/qbe
tasks:
- setup: |
    # work around bugs in qemu-binfmt
    sudo sed -i -e '/qemu_suffix:=/d' -e 's/printf/env &/' /etc/init.d/qemu-binfmt
    sudo /etc/init.d/qemu-binfmt start
    curl -O http://musl.cc/aarch64-linux-musl-cross.tgz
    tar --warning=no-unknown-keyword -xzf aarch64-linux-musl-cross.tgz
- build: |
    PATH=$HOME/qbe/obj:$HOME/aarch64-linux-musl-cross/bin:$PATH
    cd qbe
    cat >config.h <<EOF
    #define Defasm Gaself
    #define Deftgt T_arm64
    EOF
    make
    cd ../cproc
    ./configure \
      --target=aarch64-linux-musl \
      --with-ldso="$HOME/aarch64-linux-musl-cross/aarch64-linux-musl/lib/libc.so"
    make all check bootstrap
    file stage2/cproc stage2/cproc-qbe
triggers:
- action: email
  condition: failure
  to: "<~mcf/cproc@lists.sr.ht>"
